[package]
name = "adventofcode2017"
version = "0.1.0"
authors = ["Daniel Vigovszky <daniel.vigovszky@gmail.com>"]

[dependencies]
multiarray = "0.1.3"
regex = "0.2.3"
lazy_static = "1.0.0"
hex = "0.3.1"
linked-list = "0.0.3"
